#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt update
sudo apt install -y nginx

# Create custom 404 page
echo "<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/html/404.html

# Update Nginx configuration
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html; \
    location = /404.html { \
        internal; \
    }' /etc/nginx/sites-available/default

sudo nginx -t && sudo systemctl reload nginx
